sudo: true
dist: trusty

os:
  - linux
  - osx
osx_image: xcode8.2

compiler:
  - gcc
  - clang

language: node_js

node_js:
  - "7.9.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - desktop-file-utils
      - xdg-utils

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache
before_install:
  - "[[ ${TRAVIS_OS_NAME} = linux ]] && export CXX=g++-4.8 || echo 'skipped'"

install:
  - node --version
  - yarn --version
  # also downloads the build for release version
  - NODE_ENV=test yarn install

script:
  # - yarn run lint
  - yarn test
